### PR TITLE
feat: add param_count as a tag

### PR DESCRIPTION
**Pull request by zachdaniel**

### CODE REVIEW

**Comment by GregMefford** [comment]
Do you have a reference to when this was added to the `Ecto.LogEntry` struct, to make sure we have the appropriate version requirements specified in `mix.exs`?

**Comment by zachdaniel** [comment]
Great question! I should probably just only add this update if the params key is there, that way we are good to go for any version. Does that sound okay?

**Comment by GregMefford** [comment]
That sounds safer for sure. 👍

**Comment by zachdaniel** [comment]
@GregMefford done. Good catch!

**Pull request merged**
